kind: source
spec:
  name: "bitly"
  registry: "grpc"
  path: "localhost:7777"
  tables: ['*']
  destinations: ["sqlite"]
  spec:
    group_id: ${BITLY_GROUP_ID}
    api_token: ${BITLY_API_TOKEN}
    extract_utm: true
    countries_summary_unit: "month"
    referrers_summary_unit: "month"
    only:
      - bit.ly/1234567
      - bit.ly/2234567
---
kind: destination
spec:
  name: sqlite
  path: cloudquery/sqlite
  version: "v2.4.11"
  spec:
    connection_string: ./db.sqlite